In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import os
import h5py
from src.helper.paths import BASELINES_PATH
from partglot.utils.simple_utils import unpickle_data
from src.helper.visualization import visualize_pointcloud, visualize_pointclouds_parts_partglot

PosixPath('/home/bellatini/DL3D-Practical/Baselines')

In [3]:
data_dir = BASELINES_PATH / 'PartGlot/data'

h5_data = h5py.File(data_dir / "shapenet_partseg_chair_bsp.h5")
segs_data = h5_data["data"][:].astype(np.float32)
segs_mask = h5_data["mask"][:].astype(np.float32)

groundtruths, signed_distances = unpickle_data(data_dir / "shapenet_partseg_chair_label_and_sd.pkl")

In [116]:
segs_data[0].shape, segs_mask[0].shape, groundtruths[0].shape, signed_distances[0].shape

((50, 512, 3), (50,), (2691,), (2691, 25))

In [6]:
visualize_pointclouds_parts_partglot(point_clouds=segs_data[0])

Output()

In [74]:
var = segs_mask
shape = var.shape
uniques = np.unique(var, return_counts=True)
distr = np.round(var.mean(axis=0) * 100)
rowwise_cnt = np.unique(var.sum(axis=1), return_counts=True)

print(f"var_name: segs_mask\n")
print(f"shape: {shape}\n")
print(f"var:\n{var}\n")
print(f"uniques:\n{uniques}\n")
print(f"elementwise distr:\n{distr}\n")
print(f"rowwise_cnt:\n{rowwise_cnt}\n")

var_name: segs_mask

shape: (3746, 50)

var:
[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]

uniques:
(array([0., 1.], dtype=float32), array([118182,  69118]))

elementwise distr:
[100. 100. 100. 100. 100. 100. 100.  99.  98.  96.  93.  89.  84.  79.
  73.  65.  58.  51.  44.  39.  32.  28.  23.  20.  16.  13.  11.   9.
   7.   6.   4.   3.   2.   1.   1.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.]

rowwise_cnt:
(array([ 3.,  4.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
       17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.,
       30., 31., 32., 33., 34., 35., 36., 37., 38.], dtype=float32), array([  1,   1,   2,  18,  39,  72, 129, 150, 185, 187, 242, 291, 272,
       249, 242, 216, 241, 164, 166, 143, 129, 110,  86,  72,  66,  66,
        47,  45,  49,  28,  16,  10,   6,   4,   2]))

