In [3]:
import h5py
from src.helper.visualization import visualize_pointclouds_parts_partglot
import numpy as np
data_path = '/home/bellatini/DL3D-Practical/data/partglot_email/shapenet_chairs_only_in_game_10000.h5'
cmap = [0xff0000, 0x00ff00, 0x0000ff, 0xff00ff, 0xffff00, 0x00ffff]

h5_data = h5py.File(data_path)

idx = 3
verbose = True
print(list(h5_data.keys())) if verbose else None
print(h5_data['data'],h5_data['data'][:] ) if verbose else None
points = h5_data['data'][:]

visualize_pointclouds_parts_partglot(points[idx:idx+1], point_size=0.01, opacity=0.4, part_colors=cmap)


['data']
<HDF5 dataset "data": shape (4511, 10000, 3), type "<f8"> [[[-0.24611579  0.30817853 -0.09441186]
  [-0.0998033  -0.09681111 -0.14471348]
  [-0.11670284  0.02632374  0.06490469]
  ...
  [-0.26137     0.25918073  0.05206986]
  [ 0.08680589  0.01862456  0.16788353]
  [-0.00313709  0.02470448  0.20487346]]

 [[ 0.09447153  0.06572421  0.34238624]
  [-0.150263    0.20062846  0.00261817]
  [-0.150263    0.00615564  0.03046863]
  ...
  [-0.171691    0.07233076  0.24388324]
  [ 0.12258152  0.02699537 -0.17585737]
  [-0.04761975 -0.03000127 -0.15904982]]

 [[ 0.31229196 -0.01957314  0.10632622]
  [-0.20221097  0.10380762 -0.10498691]
  [-0.30780425 -0.104422   -0.0646586 ]
  ...
  [ 0.32783695 -0.03442644 -0.17372932]
  [-0.223472    0.10232076  0.01948494]
  [-0.03794452 -0.04220297 -0.09003432]]

 ...

 [[-0.14872674 -0.03222396  0.15311399]
  [ 0.164824   -0.06536825 -0.13700701]
  [-0.11377573 -0.08815984  0.185465  ]
  ...
  [-0.14092549 -0.36736079  0.16483138]
  [ 0.06776513 -0

Output()

In [2]:
# need to sort output data from bspnet ? why and how ? check out the preprocessing script
from src.partglot.utils.simple_utils import unpickle_data
from src.helper.paths import BASELINES_PATH
data_dir = BASELINES_PATH / 'PartGlot/data'
model_path = BASELINES_PATH / 'PartGlot/checkpoints/pn_agnostic.ckpt'

from src.partglot.utils.predict import get_loaded_model
partglot, partglot_dm = get_loaded_model(data_dir=data_dir, model_path=model_path)
partglot_dm.sorted_sn

['1006be65e7bc937e9141f9b58470d646',
 '100b18376b885f206ae9ad7e32c4139d',
 '1013f70851210a618f2e765c4a8ed3d',
 '1016f4debe988507589aae130c1f06fb',
 '1022fe7dd03f6a4d4d5ad9f13ac9f4e7',
 '1028b32dc1873c2afe26a3ac360dbd4',
 '1033ee86cc8bac4390962e4fb7072b86',
 '103a60f3b09107df2da1314e036b435e',
 '103b75dfd146976563ed57e35c972b4b',
 '104256e5bb73b0b719fb4103277a6b93',
 '1049953406c81b237eaeab1f0c9120b7',
 '1055f78d441d170c4f3443b22038d340',
 '1063d4fcd366de4060e37b3f76995f8b',
 '106a0dbaead5066519fb4103277a6b93',
 '106e9487a1d47ff1a09cb462b3e723e2',
 '1079635b3da12a812cee4bf5d0f11ffe',
 '107ed94869ed6f1be13496cd332ce78f',
 '108238b535eb293cd79b19c7c4f0e293',
 '1093d35c2ac73bb74ca84d60642ec7e8',
 '10991b3b01cc6cc99982a4d6320875e',
 '10a1783f635b3fc181dff5c2e57ad46e',
 '10c08a28cae054e53a762233fffc49ea',
 '10d174a00639990492d9da2668ec34c',
 '10d5c2f88b60bbf5febad4f49b26ec52',
 '10dc303144fe5d668d1b9a1d97e2846',
 '10e523060bb5b51f9ee9f382b1dfb770',
 '11040f463a3895019fb4103277a6b93',
 '11172

In [16]:
from src.partglot.utils.partglot_bspnet_preprocess import convert_supersegs_to_pointclouds
convert_supersegs_to_pointclouds()


In [10]:

game_data.sorted_sn

AttributeError: 'DataFrame' object has no attribute 'sorted_sn'