In [216]:
import h5py
from src.helper.visualization import visualize_pointclouds_parts_partglot
import numpy as np
bsp_net_data_path = '/home/bellatini/DL3D-Practical/Baselines/BSP-NET-pytorch/data/data_per_category/03001627_seg_chair/03001627_seg256.hdf5'
bsp_net_data_path = '/home/bellatini/DL3D-Practical/Baselines/BSP-NET-pytorch/data/data_per_category/03001627_chair/03001627_vox256_img_test.hdf5'
cmap = [0xff0000, 0x00ff00, 0x0000ff, 0xff00ff, 0xffff00, 0x00ffff]


In [7]:
h5_data = h5py.File(bsp_net_data_path)

In [9]:
list(h5_data.keys())

['pixels',
 'points_16',
 'points_32',
 'points_64',
 'values_16',
 'values_32',
 'values_64',
 'voxels']

In [124]:
resolutions = [16, 32, 64] 
for r in resolutions:
    print(f"\nr={r}")
    print(h5_data['pixels'])
    print(h5_data[f'points_{r}'])
    print(h5_data[f'values_{r}'])
    print(h5_data['voxels'])
    
    
res = resolutions[2]

res


r=16
<HDF5 dataset "pixels": shape (1356, 24, 137, 137), type "|u1">
<HDF5 dataset "points_16": shape (1356, 4096, 3), type "|u1">
<HDF5 dataset "values_16": shape (1356, 4096, 1), type "|u1">
<HDF5 dataset "voxels": shape (1356, 64, 64, 64, 1), type "|u1">

r=32
<HDF5 dataset "pixels": shape (1356, 24, 137, 137), type "|u1">
<HDF5 dataset "points_32": shape (1356, 4096, 3), type "|u1">
<HDF5 dataset "values_32": shape (1356, 4096, 1), type "|u1">
<HDF5 dataset "voxels": shape (1356, 64, 64, 64, 1), type "|u1">

r=64
<HDF5 dataset "pixels": shape (1356, 24, 137, 137), type "|u1">
<HDF5 dataset "points_64": shape (1356, 16384, 3), type "|u1">
<HDF5 dataset "values_64": shape (1356, 16384, 1), type "|u1">
<HDF5 dataset "voxels": shape (1356, 64, 64, 64, 1), type "|u1">


64

In [123]:
h5_data['pixels'][0][0].mean(axis=0)
h5_data['pixels'][0][0]
h5_data['pixels'][0][0][27]

array([255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 248, 150,  87,  88,  88,  89,
       103, 241, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255], dtype=uint8)

In [134]:
print(h5_data[f'values_{r}'][:].shape)
np.unique(h5_data[f'values_{r}'][0], return_counts=True)

(1356, 16384, 1)


(array([0, 1], dtype=uint8), array([9838, 6546]))

In [231]:
idx = 5

pc = h5_data[f'points_{res}'][idx]

mask = h5_data[f'values_{r}'][idx].astype(bool)
# print(f"mask.shape={mask.shape}")
# print(f"mask={mask}")
mask = (np.ones((mask.shape[0], 3)) * mask).astype(bool)
# print(f"mask.shape={mask.shape}")
mask

pc[mask].reshape((-1, 3)).shape, pc.shape

segmented_pc = np.array([
    pc[mask].reshape((-1,3)), 
    # pc[~mask].reshape((-1,3))
    ])

# pc = np.array([h5_data[f'points_{64}'][idx]])
visualize_pointclouds_parts_partglot(segmented_pc, point_size=2, opacity=0.4, part_colors=cmap)

Visualization rendering started...


Output()

mask.shape=(16384, 1)
mask=[[False]
 [False]
 [ True]
 ...
 [False]
 [False]
 [False]]
mask.shape=(16384, 3)


array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])

/tmp/ipykernel_1062166/2620933494.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  segmented_pc = np.array([pc[mask].reshape((-1,3)), pc[~mask].reshape((-1,3))])


Visualization rendering started...


Output()

(1, 4096, 3)

In [16]:
list(h5_data.keys())

['pixels',
 'points_16',
 'points_32',
 'points_64',
 'values_16',
 'values_32',
 'values_64',
 'voxels']

In [17]:
137*137

18769