In [8]:
import h5py
from src.helper.visualization import visualize_pointclouds_parts_partglot
import numpy as np
data_path = '/home/bellatini/DL3D-Practical/data/partglot_email/shapenet_chairs_only_in_game_10000.h5'
cmap = [0xff0000, 0x00ff00, 0x0000ff, 0xff00ff, 0xffff00, 0x00ffff]

h5_data = h5py.File(data_path)

idx = 1
verbose = True
print(list(h5_data.keys())) if verbose else None
print(h5_data['data'],h5_data['data'][:] ) if verbose else None
points = h5_data['data'][:]

visualize_pointclouds_parts_partglot(points[idx:idx+1], point_size=0.01, opacity=0.4, part_colors=cmap)


['data']
<HDF5 dataset "data": shape (4511, 10000, 3), type "<f8"> [[[-0.24611579  0.30817853 -0.09441186]
  [-0.0998033  -0.09681111 -0.14471348]
  [-0.11670284  0.02632374  0.06490469]
  ...
  [-0.26137     0.25918073  0.05206986]
  [ 0.08680589  0.01862456  0.16788353]
  [-0.00313709  0.02470448  0.20487346]]

 [[ 0.09447153  0.06572421  0.34238624]
  [-0.150263    0.20062846  0.00261817]
  [-0.150263    0.00615564  0.03046863]
  ...
  [-0.171691    0.07233076  0.24388324]
  [ 0.12258152  0.02699537 -0.17585737]
  [-0.04761975 -0.03000127 -0.15904982]]

 [[ 0.31229196 -0.01957314  0.10632622]
  [-0.20221097  0.10380762 -0.10498691]
  [-0.30780425 -0.104422   -0.0646586 ]
  ...
  [ 0.32783695 -0.03442644 -0.17372932]
  [-0.223472    0.10232076  0.01948494]
  [-0.03794452 -0.04220297 -0.09003432]]

 ...

 [[-0.14872674 -0.03222396  0.15311399]
  [ 0.164824   -0.06536825 -0.13700701]
  [-0.11377573 -0.08815984  0.185465  ]
  ...
  [-0.14092549 -0.36736079  0.16483138]
  [ 0.06776513 -0

Output()

In [3]:
import h5py

In [4]:
bsp_data = h5py.File(data_path)

In [18]:
points[]

['pixels',
 'points_16',
 'points_32',
 'points_64',
 'values_16',
 'values_32',
 'values_64',
 'voxels']

In [25]:
bsp_data['voxels'].shape

(8762, 64, 64, 64, 1)

In [27]:
bsp_data['pixels'].shape


(8762, 24, 137, 137)

In [31]:
bsp_data['values_16'].shape


(8762, 4096, 1)

In [9]:
bsp_data.items()

ItemsViewHDF5(<HDF5 file "all_vox256_img_test.hdf5" (mode r)>)